-- Baseline marker: intentionally a no-op.
--
-- Hive schema management is HYBRID:
--
--   * The inline idempotent DDL in api/src/db.rs (the SCHEMA / SCHEMA_SEARCH
--     constants and the ALTER list in migrate()) is the base schema and stays
--     authoritative for what a table looks like.
--   * Files in this directory are sqlx migrations, reserved for RESHAPES the
--     inline CREATE-IF-NOT-EXISTS style cannot express (column type changes,
--     data rewrites, drops, backfills, ...). migrate() runs them FIRST, before
--     the inline DDL.
--   * Because migrations run first, every migration must tolerate BOTH a fresh
--     database (the inline DDL has not run yet, so tables may be missing —
--     guard everything with IF EXISTS or information_schema probes qualified
--     by `table_schema = current_schema()`) AND an existing database still on
--     the old shape.
--   * The same PR that adds a reshape migration updates the inline constants
--     to the final shape, so fresh installs land there directly and the
--     migration no-ops for them.
--   * Never edit an applied migration — sqlx checksums each file into
--     _sqlx_migrations and refuses to start on mismatch. Add a new file.
SELECT 1;
